#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.11
# from Racc grammer file "".
#

require 'racc/parser.rb'


class Tinyc < Racc::Parser

module_eval(<<'...end compiler.y/module_eval...', 'compiler.y', 371)

  class Object
    def initialize(name, level, type, offset)
      @name = name
      @level = level
      @type = type
      @offset = offset
    end
    def changeType(type) 
      @type = type
    end
    attr_reader :level, :type
    attr_accessor :name, :offset
  end

  def initialize()
    @stack = []
    @level = 0
    @error_stack = []
    @error_num = 0
    @add_sp = 0
  end

  def popStack(level)
    while @stack[@stack.length-1].level >= level
      if @stack[@stack.length-1].type == 'VAR'
        if @stack[@stack.length-1].level == 1
	  @add_sp -= 4
        else
	  @add_sp += 4
        end
      end
      @stack.pop
    end
  end

  def findObject(name, type)
    ret = {}
    ret['level'] = -1
    ret['size'] = -1
    i = @stack.length-1
    while i >= 0
      if @stack[i].name == name && @stack[i].type == type
        ret['level'] = @stack[i].level
        ret['size'] = @stack[i].offset
        break
      end
      i -= 1
    end
    return ret
  end

  def insertStackUndefFun(name, size)
    obj = Object.new(name, 0, 'UNDEFFUN', size)
    i = @stack.length - 1
    while i >= 0
      if @stack[i].level == 0
        break
      else
	i -= 1
      end
    end
    if i > 0
      @stack = @stack[0..(i-1)] + [obj] + @stack[i..(@stack.length-1)]
    else
      @stack = [obj] + @stack
    end	
  end

  def changeFunctionInfo(name, size)
    i = @stack.length - 1
    while i >= 0
      if @stack[i].type == 'FUN'
	@stack[i].name = name
	@stack[i].offset = size
	break
      end
      i -= 1
    end
  end

  def error(type, name, level)
    @error_num += 1
    print "error: "
    if type == 0
      puts "Variable '#{name}' is already defined at same level(level#{level})."
    elsif type == 1
      puts "Function '#{name}' is already defined at same level(level#{level})."
    elsif type == 2
      puts "Parameter-length of function '#{name}' is #{level}."
    elsif type == 3
      puts "Variable '#{name}' is NOT defined."
    else
      puts "Undefined type."
    end
  end

  def warning(type, name, level)
    print "warning: "
    if type == 0
      puts "Variable '#{name}' is already defined at level #{level}."
    elsif type == 1
      puts "Function '#{name}' is already defined at level #{level}."
    elsif type == 2
      puts "Function '#{name}' is NOT defined."
    else
      puts "Undefined type."
    end
  end
  
  def parse(str)
    @q = []
    until str.empty?
      # puts str.inspect
      case str
      when /\A\s+/
      when /\A\d+/
        @q.push [:CONSTANT, $&.to_i]
      when /\A(&&)/
        @q.push [:LOGICALAND, $&]
      when /\A(\|\|)/
        @q.push [:LOGICALOR, $&]
      when /\A(int)/
        @q.push [:DATATYPE, $&]
      when /\A(if)/
        @q.push [:IF, $&]
      when /\A(else)/
        @q.push [:ELSE, $&]
      when /\A(while)/
        @q.push [:WHILE, $&]
      when /\A(<=)/
        @q.push [:LE, $&]
      when /\A(>=)/
        @q.push [:GE, $&]
      when /\A(==)/
        @q.push [:EQUAL, $&]
      when /\A(!=)/
        @q.push [:NOTEQUAL, $&]
      when /\A(return)/
        @q.push [:RETURN, $&]
      when /\A[a-zA-Z]\w*/
	@q.push [:IDENTIFIER, $&]
      when /\A.|\n/o
        s = $&
        @q.push [s, s]
      end
      str = $'
    end
    @q.push [false, '$end']
    do_parse
  end

  def next_token
    @q.shift
  end

...end compiler.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    37,    68,    38,    39,    73,    74,     6,   102,     5,    37,
    59,    38,    39,    65,    53,    71,    72,   103,    56,    28,
    59,    63,    34,    53,    45,    55,    67,    56,    28,    73,
    74,    34,    53,    45,    55,    37,    56,    38,    39,    61,
    71,    72,    80,    55,    37,   104,    38,    39,    59,    53,
    77,    78,    60,    56,    28,    75,    76,    34,    53,    45,
    55,    30,    56,    28,    73,    74,    34,    53,    45,    55,
    37,    56,    38,    39,    68,    71,    72,    80,    55,    69,
    70,    66,    67,   105,    53,   106,    53,    16,    56,    28,
    56,    30,    34,    28,    45,    55,    80,    55,    53,    21,
    53,    16,    56,    53,    56,    75,    76,    56,    80,    55,
    80,    55,    53,    80,    55,    53,    56,    53,    23,    56,
    53,    56,    80,    55,    56,    80,    55,    45,    55,    53,
    45,    55,    53,    56,    53,    22,    56,    53,    56,    80,
    55,    56,    45,    55,    45,    55,    53,    80,    55,    53,
    56,    53,    21,    56,    53,    56,    45,    55,    56,    45,
    55,    80,    55,    53,    80,    55,    53,    56,    53,    16,
    56,    14,    56,    80,    55,    11,    45,    55,    45,    55,
    58,    59,    12,    13,    69,    70,    77,    78,    77,    78,
    75,    76,    75,    76,    75,    76,    85,    59,    10,   110,
     5 ]

racc_action_check = [
   110,    46,   110,   110,    48,    48,     1,    81,     1,   103,
    81,   103,   103,    44,   110,    48,    48,    83,   110,   110,
    83,    40,   110,   103,   110,   110,    80,   103,   103,    92,
    92,   103,    77,   103,   103,    42,    77,    42,    42,    38,
    92,    92,    77,    77,   104,    84,   104,   104,    84,    42,
    50,    50,    37,    42,    42,    49,    49,    42,   104,    42,
    42,    33,   104,   104,    93,    93,   104,    74,   104,   104,
    31,    74,    31,    31,    86,    93,    93,    74,    74,    47,
    47,    45,    45,    88,    31,    90,    73,    30,    31,    31,
    73,    29,    31,    25,    31,    31,    73,    73,    72,    23,
    71,    21,    72,    70,    71,    97,    97,    70,    72,    72,
    71,    71,    69,    70,    70,    68,    69,    56,    20,    68,
    67,    56,    69,    69,    67,    68,    68,    56,    56,    53,
    67,    67,    60,    53,    61,    18,    60,    78,    61,    53,
    53,    78,    60,    60,    61,    61,   106,    78,    78,    66,
   106,    65,    17,    66,    76,    65,   106,   106,    76,    66,
    66,    65,    65,    75,    76,    76,    59,    75,    39,    13,
    59,    10,    39,    75,    75,     6,    59,    59,    39,    39,
    35,    35,     8,     8,    91,    91,    99,    99,    98,    98,
    94,    94,    95,    95,    96,    96,    62,    62,     5,   107,
     0 ]

racc_action_pointer = [
   198,     6,   nil,   nil,   nil,   171,   175,   nil,   157,   nil,
   150,   nil,   nil,   142,   nil,   nil,   nil,   150,   112,   nil,
    92,    74,   nil,    97,   nil,    71,   nil,   nil,   nil,    89,
    60,    67,   nil,    59,   nil,   155,   nil,    31,    18,   151,
    -3,   nil,    32,   nil,     1,    61,   -10,    70,    -3,    39,
    37,   nil,   nil,   112,   nil,   nil,   100,   nil,   nil,   149,
   115,   117,   171,   nil,   nil,   134,   132,   103,    98,    95,
    86,    83,    81,    69,    50,   146,   137,    15,   120,   nil,
     5,   -16,   nil,    -6,    22,   nil,    63,   nil,    60,   nil,
    59,   175,    22,    57,   174,   176,   178,    89,   175,   173,
   nil,   nil,   nil,     6,    41,   nil,   129,   195,   nil,   nil,
    -3,   nil ]

racc_action_default = [
   -67,   -67,    -1,    -3,    -4,   -67,   -67,    -2,   -67,    -6,
    -8,   112,    -5,   -67,    -9,    -7,    -8,   -15,   -67,   -12,
   -14,   -67,   -10,   -67,   -16,   -67,   -13,   -11,   -24,   -29,
   -67,   -33,   -26,   -28,   -17,   -67,   -19,   -67,   -67,   -67,
   -67,   -30,   -32,   -34,   -36,   -60,   -38,   -40,   -42,   -45,
   -50,   -53,   -56,   -67,   -58,   -61,   -67,   -27,   -18,   -67,
   -67,   -67,   -67,   -25,   -31,   -67,   -67,   -66,   -67,   -67,
   -67,   -67,   -67,   -67,   -67,   -67,   -67,   -67,   -67,   -57,
   -60,   -67,   -35,   -67,   -67,   -23,   -39,   -37,   -67,   -63,
   -65,   -41,   -43,   -44,   -46,   -47,   -48,   -49,   -51,   -52,
   -54,   -55,   -62,   -67,   -67,   -59,   -67,   -20,   -22,   -64,
   -67,   -21 ]

racc_goto_table = [
    41,    82,    79,    62,    15,    40,    32,    19,    87,    89,
    57,    64,    24,    26,    94,    95,    96,    97,    92,    93,
    81,    98,    99,    31,    83,    84,   100,   101,     2,     7,
    25,    33,    29,    42,    17,    86,    91,    20,    27,    18,
     1,    88,    90,   nil,   nil,   nil,   nil,   nil,   109,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   107,   108,   nil,   nil,   nil,   nil,   nil,   111 ]

racc_goto_check = [
    13,    20,    27,    14,     6,    16,     3,    12,    20,    20,
     3,    13,     6,    12,    25,    25,    25,    25,    24,    24,
    14,    26,    26,    15,    14,    14,    27,    27,     2,     2,
    11,    17,    18,    19,    10,    22,    23,     9,     8,     7,
     1,    30,    31,   nil,   nil,   nil,   nil,   nil,    20,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    13,    13,   nil,   nil,   nil,   nil,   nil,    13 ]

racc_goto_pointer = [
   nil,    40,    28,   -23,   nil,   nil,    -9,    22,    13,    20,
    20,     8,   -10,   -31,   -36,    -6,   -26,     2,     4,     2,
   -58,   nil,   -30,   -32,   -51,   -57,   -54,   -51,   nil,   nil,
   -26,   -25 ]

racc_goto_default = [
   nil,   nil,   nil,     3,     4,     8,     9,   nil,    36,   nil,
   nil,   nil,   nil,   nil,    35,   nil,   nil,   nil,   nil,   nil,
    43,    44,    46,    47,    48,    49,    50,    51,    52,    54,
   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 30, :_reduce_1,
  2, 30, :_reduce_2,
  1, 31, :_reduce_3,
  1, 31, :_reduce_4,
  3, 32, :_reduce_5,
  1, 34, :_reduce_6,
  3, 34, :_reduce_7,
  1, 35, :_reduce_none,
  0, 39, :_reduce_9,
  0, 40, :_reduce_10,
  8, 33, :_reduce_11,
  1, 38, :_reduce_12,
  3, 38, :_reduce_13,
  1, 36, :_reduce_none,
  0, 36, :_reduce_15,
  2, 41, :_reduce_16,
  1, 42, :_reduce_17,
  2, 42, :_reduce_18,
  1, 42, :_reduce_none,
  5, 42, :_reduce_20,
  7, 42, :_reduce_21,
  5, 42, :_reduce_22,
  3, 42, :_reduce_23,
  0, 47, :_reduce_24,
  5, 37, :_reduce_25,
  1, 46, :_reduce_none,
  2, 46, :_reduce_27,
  1, 44, :_reduce_none,
  0, 44, :_reduce_none,
  1, 48, :_reduce_none,
  2, 48, :_reduce_31,
  1, 45, :_reduce_none,
  0, 45, :_reduce_none,
  1, 43, :_reduce_34,
  3, 43, :_reduce_35,
  1, 49, :_reduce_none,
  3, 49, :_reduce_37,
  1, 50, :_reduce_none,
  3, 50, :_reduce_39,
  1, 51, :_reduce_none,
  3, 51, :_reduce_41,
  1, 52, :_reduce_none,
  3, 52, :_reduce_43,
  3, 52, :_reduce_44,
  1, 53, :_reduce_none,
  3, 53, :_reduce_46,
  3, 53, :_reduce_47,
  3, 53, :_reduce_48,
  3, 53, :_reduce_49,
  1, 54, :_reduce_none,
  3, 54, :_reduce_51,
  3, 54, :_reduce_52,
  1, 55, :_reduce_none,
  3, 55, :_reduce_54,
  3, 55, :_reduce_55,
  1, 56, :_reduce_none,
  2, 56, :_reduce_57,
  1, 57, :_reduce_none,
  4, 57, :_reduce_59,
  1, 58, :_reduce_60,
  1, 58, :_reduce_none,
  3, 58, :_reduce_62,
  1, 60, :_reduce_63,
  3, 60, :_reduce_64,
  1, 59, :_reduce_none,
  0, 59, :_reduce_none ]

racc_reduce_n = 67

racc_shift_n = 112

racc_token_table = {
  false => 0,
  :error => 1,
  :DATATYPE => 2,
  :IF => 3,
  :ELSE => 4,
  :WHILE => 5,
  :RETURN => 6,
  :LE => 7,
  :GE => 8,
  :EQUAL => 9,
  :NOTEQUAL => 10,
  :LOGICALAND => 11,
  :LOGICALOR => 12,
  "*" => 13,
  "/" => 14,
  "%" => 15,
  "+" => 16,
  "-" => 17,
  "<" => 18,
  ">" => 19,
  "=" => 20,
  "(" => 21,
  "{" => 22,
  ")" => 23,
  "}" => 24,
  ";" => 25,
  "," => 26,
  :IDENTIFIER => 27,
  :CONSTANT => 28 }

racc_nt_base = 29

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "DATATYPE",
  "IF",
  "ELSE",
  "WHILE",
  "RETURN",
  "LE",
  "GE",
  "EQUAL",
  "NOTEQUAL",
  "LOGICALAND",
  "LOGICALOR",
  "\"*\"",
  "\"/\"",
  "\"%\"",
  "\"+\"",
  "\"-\"",
  "\"<\"",
  "\">\"",
  "\"=\"",
  "\"(\"",
  "\"{\"",
  "\")\"",
  "\"}\"",
  "\";\"",
  "\",\"",
  "IDENTIFIER",
  "CONSTANT",
  "$start",
  "program",
  "external_declaration",
  "declaration",
  "function_definition",
  "declarator_list",
  "declarator",
  "parameter_type_list_opt",
  "compound_statement",
  "parameter_type_list",
  "@1",
  "@2",
  "parameter_declaration",
  "statement",
  "expression",
  "declaration_list_opt",
  "statement_list_opt",
  "declaration_list",
  "@3",
  "statement_list",
  "assign_expr",
  "logical_OR_expr",
  "logical_AND_expr",
  "equality_expr",
  "relational_expr",
  "add_expr",
  "mult_expr",
  "unary_expr",
  "posifix_expr",
  "primary_expr",
  "argument_expression_list_opt",
  "argument_expression_list" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'compiler.y', 29)
  def _reduce_1(val, _values, result)
    	  if @error_num > 0
            result = ''
          end
        
    result
  end
.,.,

module_eval(<<'.,.,', 'compiler.y', 35)
  def _reduce_2(val, _values, result)
    	  if @error_num > 0
            result = ''
          else
	    result = val[0] + val[1] 
          end
        
    result
  end
.,.,

module_eval(<<'.,.,', 'compiler.y', 44)
  def _reduce_3(val, _values, result)
    	result = val[0]
      
    result
  end
.,.,

module_eval(<<'.,.,', 'compiler.y', 48)
  def _reduce_4(val, _values, result)
    	result = [val[0]]
      
    result
  end
.,.,

module_eval(<<'.,.,', 'compiler.y', 53)
  def _reduce_5(val, _values, result)
    	  result = []
	  for i in val[1]
	    check = findObject(i, 'VAR')
	    if check['level'] == @level
	      error(0, i, check['level'])
	    else
  	      check2 = findObject(i, 'FUN')
	      if check2['level'] == @level
	        error(1, i, check2['level']) 
	      else
	        if check['level'] >= 0
	          warning(0, i, check['level'])
                end
                if check2['level'] >= 0
	          warning(1, i, check2['level'])
		end
		@stack.push(Object.new(i, @level, 'VAR', 0))
	      end
	    end
	    @add_sp -= 4
	    i += ':VAR:level' + @level.to_s
            if @level > 0
              i += "(#{@add_sp})"
	    end
	    result += [ [val[0], i ] ]
	  end
        
    result
  end
.,.,

module_eval(<<'.,.,', 'compiler.y', 83)
  def _reduce_6(val, _values, result)
    	  result = [val[0]]
        
    result
  end
.,.,

module_eval(<<'.,.,', 'compiler.y', 87)
  def _reduce_7(val, _values, result)
    	  result += [val[2]]
        
    result
  end
.,.,

# reduce 8 omitted

module_eval(<<'.,.,', 'compiler.y', 94)
  def _reduce_9(val, _values, result)
              @level += 1
	  @add_sp = 4
	  @stack.push(Object.new('_UNKNOWN', 0, 'FUN', 0))
	
    result
  end
.,.,

module_eval(<<'.,.,', 'compiler.y', 100)
  def _reduce_10(val, _values, result)
    	  @add_sp = 0
	
    result
  end
.,.,

module_eval(<<'.,.,', 'compiler.y', 104)
  def _reduce_11(val, _values, result)
    	  popStack(@level)
	  @level -= 1
  	  check = findObject(val[1], 'VAR')
	  if check['level'] >= 0
	    error(0, val[1], check['level'])
	  else
  	    check2 = findObject(val[1], 'FUN')
	    if check2['level'] >= 0
	      error(1, val[1], check2['level'])
	    else
	      if val[4] == nil
                changeFunctionInfo(val[1], 0)
	      else
                changeFunctionInfo(val[1], val[4].length)
              end
	    end
	  end
	  while @error_stack.length > 0
            obj = @error_stack.pop
  	    check = findObject(obj.name, 'FUN')
	    if check['level'] < 0
	      warning(2, obj.name, -1)
	      insertStackUndefFun(obj.name, obj.offset)
	    elsif obj.offset != check['size']
	      error(2, obj.name, check['size'])
	    end	    
          end
	  result = [ [val[0], val[1]+':FUN:level0'], val[4], val[7] ]
        
    result
  end
.,.,

module_eval(<<'.,.,', 'compiler.y', 136)
  def _reduce_12(val, _values, result)
    	  result = [val[0]]
	
    result
  end
.,.,

module_eval(<<'.,.,', 'compiler.y', 140)
  def _reduce_13(val, _values, result)
              result = val[0] + [val[2]]
        
    result
  end
.,.,

# reduce 14 omitted

module_eval(<<'.,.,', 'compiler.y', 146)
  def _reduce_15(val, _values, result)
    	result = []
      
    result
  end
.,.,

module_eval(<<'.,.,', 'compiler.y', 151)
  def _reduce_16(val, _values, result)
    	  check = findObject(val[1], 'VAR')
	  if check['level'] == @level
	    error(0, val[1], check['level'])
	  else
  	    check2 = findObject(val[1], 'FUN')
	    if check2['level'] == @level
	      error(1, val[1], check2['level']) 
	    else
	      if check['level'] >= 0
	        warning(0, val[1], check['level'])
              end
	      if check2['level'] >= 0
	        warning(1, val[1], check2['level'])
	      end
  	      @stack.push(Object.new(val[1], @level, 'VAR', 0))
	      @add_sp += 4
	      val[1] += ':VAR:level' + @level.to_s + "(#{@add_sp})"
	    end
	  end
	  result = [val[0], val[1]]
        
    result
  end
.,.,

module_eval(<<'.,.,', 'compiler.y', 175)
  def _reduce_17(val, _values, result)
    	  result = ''
        
    result
  end
.,.,

module_eval(<<'.,.,', 'compiler.y', 179)
  def _reduce_18(val, _values, result)
    	  result = val[0]
        
    result
  end
.,.,

# reduce 19 omitted

module_eval(<<'.,.,', 'compiler.y', 184)
  def _reduce_20(val, _values, result)
    	  result = [['IF'] + val[2] + [val[4], []]]
        
    result
  end
.,.,

module_eval(<<'.,.,', 'compiler.y', 188)
  def _reduce_21(val, _values, result)
    	  result = [['IF'] + val[2] + [val[4], val[6]]]
        
    result
  end
.,.,

module_eval(<<'.,.,', 'compiler.y', 192)
  def _reduce_22(val, _values, result)
    	  result = [['WHILE'] + val[2] + [val[4]]]
        
    result
  end
.,.,

module_eval(<<'.,.,', 'compiler.y', 196)
  def _reduce_23(val, _values, result)
    	  result = [['RETURN'] + val[1]]
        
    result
  end
.,.,

module_eval(<<'.,.,', 'compiler.y', 201)
  def _reduce_24(val, _values, result)
    	  @level += 1
        
    result
  end
.,.,

module_eval(<<'.,.,', 'compiler.y', 205)
  def _reduce_25(val, _values, result)
    	  popStack(@level)
	  @level -= 1
	  result = []
          if val[2] != nil
	    result += val[2]
	  end
	  if val[3] != nil
	    result += val[3]
	  end
        
    result
  end
.,.,

# reduce 26 omitted

module_eval(<<'.,.,', 'compiler.y', 219)
  def _reduce_27(val, _values, result)
    	  result = [val[0], val[1]]
        
    result
  end
.,.,

# reduce 28 omitted

# reduce 29 omitted

# reduce 30 omitted

module_eval(<<'.,.,', 'compiler.y', 228)
  def _reduce_31(val, _values, result)
    	  result = val[0] + val[1]
        
    result
  end
.,.,

# reduce 32 omitted

# reduce 33 omitted

module_eval(<<'.,.,', 'compiler.y', 236)
  def _reduce_34(val, _values, result)
    	  result = [val[0]]
	
    result
  end
.,.,

module_eval(<<'.,.,', 'compiler.y', 240)
  def _reduce_35(val, _values, result)
    	  result = [val[0], val[2]]
        
    result
  end
.,.,

# reduce 36 omitted

module_eval(<<'.,.,', 'compiler.y', 246)
  def _reduce_37(val, _values, result)
      	  check = findObject(val[0], 'VAR')
	  if check['level'] < 0
	    error(3, val[0], -1)
	  end
	  val[0] += ":VAR:level#{check['level']}"
	  result = ['=', val[0], val[2]]
        
    result
  end
.,.,

# reduce 38 omitted

module_eval(<<'.,.,', 'compiler.y', 257)
  def _reduce_39(val, _values, result)
    	  result = ['||', val[0], val[2]]
        
    result
  end
.,.,

# reduce 40 omitted

module_eval(<<'.,.,', 'compiler.y', 263)
  def _reduce_41(val, _values, result)
    	  result = ['&&', val[0], val[2]]
        
    result
  end
.,.,

# reduce 42 omitted

module_eval(<<'.,.,', 'compiler.y', 269)
  def _reduce_43(val, _values, result)
    	  result = ['==', val[0], val[2]]
        
    result
  end
.,.,

module_eval(<<'.,.,', 'compiler.y', 273)
  def _reduce_44(val, _values, result)
    	  result = ['!=', val[0], val[2]]
        
    result
  end
.,.,

# reduce 45 omitted

module_eval(<<'.,.,', 'compiler.y', 279)
  def _reduce_46(val, _values, result)
    	  result = ['<', val[0], val[2]]
        
    result
  end
.,.,

module_eval(<<'.,.,', 'compiler.y', 283)
  def _reduce_47(val, _values, result)
    	  result = ['>', val[0], val[2]]
        
    result
  end
.,.,

module_eval(<<'.,.,', 'compiler.y', 287)
  def _reduce_48(val, _values, result)
    	  result = ['<=', val[0], val[2]]
        
    result
  end
.,.,

module_eval(<<'.,.,', 'compiler.y', 291)
  def _reduce_49(val, _values, result)
    	  result = ['>=', val[0], val[2]]
        
    result
  end
.,.,

# reduce 50 omitted

module_eval(<<'.,.,', 'compiler.y', 297)
  def _reduce_51(val, _values, result)
    	  result = ['+', val[0], val[2]]
        
    result
  end
.,.,

module_eval(<<'.,.,', 'compiler.y', 301)
  def _reduce_52(val, _values, result)
    	  result = ['-', val[0], val[2]]
        
    result
  end
.,.,

# reduce 53 omitted

module_eval(<<'.,.,', 'compiler.y', 307)
  def _reduce_54(val, _values, result)
    	  result = ['*', val[0], val[2]]
        
    result
  end
.,.,

module_eval(<<'.,.,', 'compiler.y', 311)
  def _reduce_55(val, _values, result)
    	  result = ['/', val[0], val[2]]
        
    result
  end
.,.,

# reduce 56 omitted

module_eval(<<'.,.,', 'compiler.y', 317)
  def _reduce_57(val, _values, result)
    	  result = -(val[1].to_i).to_s
        
    result
  end
.,.,

# reduce 58 omitted

module_eval(<<'.,.,', 'compiler.y', 323)
  def _reduce_59(val, _values, result)
      	  check = findObject(val[0], 'FUN')
	  if check['level'] < 0
            if val[2] != nil
	      @error_stack.push(Object.new(val[0], 0, 'UNDEFFUN', val[2].length))
	    else
	      @error_stack.push(Object.new(val[0], 0, 'UNDEFFUN', 0))
            end
	  elsif (val[2] == nil && check['size'] != 0) || val[2].length != check['size']
	    error(2, val[0], check['size'])
	  end
          if val[2] == nil
	    result = ['FCALL',val[0], []]
	  else
	    result = ['FCALL',val[0]] + [val[2]]
          end
        
    result
  end
.,.,

module_eval(<<'.,.,', 'compiler.y', 342)
  def _reduce_60(val, _values, result)
      	  check = findObject(val[0], 'VAR')
	  if check['level'] < 0
	    error(3, val[0], -1)
	  end
	  val[0] += ":VAR:level#{check['level']}"
          result = val[0]
	
    result
  end
.,.,

# reduce 61 omitted

module_eval(<<'.,.,', 'compiler.y', 352)
  def _reduce_62(val, _values, result)
    	  result = [val[1]]
        
    result
  end
.,.,

module_eval(<<'.,.,', 'compiler.y', 357)
  def _reduce_63(val, _values, result)
    	  result = [val[0]]
        
    result
  end
.,.,

module_eval(<<'.,.,', 'compiler.y', 361)
  def _reduce_64(val, _values, result)
    	  result = val[0] + [val[2]]
        
    result
  end
.,.,

# reduce 65 omitted

# reduce 66 omitted

def _reduce_none(val, _values, result)
  val[0]
end

end   # class Tinyc


# 書き出すアセンブリファイル名
$filename = ARGV[0]
if $filename == nil
  $filename = "test.asm"
end
$file = open($filename, "w")

# 宣言された関数名のリスト
$functions = []

# 宣言されたローカル変数名(レベル含む)のリスト
$local_vars = {}

# 宣言されたIF文の数
$local_ifs = 0

# 宣言されたWHILE文の数
$local_whiles = 0

# 宣言された論理演算数
$local_logicals = 0

# 関数culcNLocal用
$n_local = 0



# アセンブリコードを生成する
def generateAssemble(tree)
  # アセンブリコードを1行書き出す
  def putsFile(a, b=nil, c=nil, d=nil)
    $file.print("#{a}") if a != nil
    $file.print("\t#{b}") if b != nil
    $file.print("\t#{c}") if c != nil
    $file.print(", #{d}") if d != nil
    $file.puts("")
  end


  # そのノードから下に伸びるノード中で使われる相対番地の絶対値の最大値を求める
  # 大域変数$n_localに書き出される
  def culcNLocal(node)
    for n in node
      if n[0] == "int"
        n[1] =~ /.+:.+:level.+\(-(.+)\)/
        $n_local = $1.to_i if $1.to_i > $n_local
      elsif n[0] == "WHILE"
        culcNLocal(n[2])
      elsif n[0] == "IF"
        culcNLocal(n[2])
        culcNLocal(n[3])
      end
    end
  end


  # 数あるいは"#{name}:#{type}:level#{level}"を、コード形式に変換して返す
  def leafToCode(leaf)
    if leaf.instance_of?(String) == true
      if $local_vars[leaf] != nil && $local_vars[leaf] >= 0
        return "[ebp+#{$local_vars[leaf]}]"
      else
        return "[ebp#{$local_vars[leaf]}]"
      end
    else
      return "#{leaf}"
    end
  end

  
  # 木を掘り進んで順番にコードを生成する
  def digTree(parent_node, child_node, lvl=-1)
    # 比較演算ノードを渡して、比較演算を行うコードを出力する
    def writeComp(base_node, lv)
      def comp(node, lev)
        # 先頭要素が比較演算子
        if node[2].instance_of?(String) == true || node[2].instance_of?(Fixnum) == true
          putsFile(nil, "mov", "eax", leafToCode(node[2]))          
          putsFile(nil, "push", "eax")
        else
          digTree(node, node[2], lev + 1)
          putsFile(nil, "push", "eax")
        end
        if node[1].instance_of?(String) == true || node[1].instance_of?(Fixnum) == true
          putsFile(nil, "mov", "eax", leafToCode(node[1]))
        else
          digTree(node, node[1], lev + 1)
        end
        putsFile(nil, "pop", "ebx")        
        putsFile(nil, "cmp", "eax", "ebx")                
        case node[0]
        when "=="
          putsFile(nil, "sete", "al")                  
        when "!="
          putsFile(nil, "setne", "al")                  
        when ">"
          putsFile(nil, "setg", "al")                  
        when "<"
          putsFile(nil, "setl", "al")                  
        when ">="
          putsFile(nil, "setge", "al")                  
        when "<="
          putsFile(nil, "setle", "al")                  
        end
        putsFile(nil, "movzx", "eax", "al")
        putsFile(nil, "cmp", "eax", 0)
      end
      
      def logical(node, lv)
        # 先頭要素が論理演算子
        case node[0]
        when "&&"
          $file.puts("; && ここから(#{node[1]}, #{node[2]})")
          putsFile(nil, "mov", "eax", "0")
          putsFile(nil, "push", "eax")          
          if node[1][0].instance_of?(String) == false || node[1][0] == "&&" || node[1][0] == "||"
            logical(node[1], lv)
          else
            comp(node[1], lv)
          end
          putsFile(nil, "cmp", "eax", "0")          
          putsFile(nil, "je", "#{$functions[$functions.length-1]}_logical#{$local_logicals}")
          if node[1][0].instance_of?(String) == false || node[2][0] == "&&" || node[2][0] == "||"
            logical(node[2], lv)
          else
            comp(node[2], lv)
          end
          putsFile(nil, "cmp", "eax", "0")          
          putsFile(nil, "je", "#{$functions[$functions.length-1]}_logical#{$local_logicals}")
          putsFile(nil, "pop", "eax")
          putsFile(nil, "mov", "eax", "1")
          putsFile(nil, "push", "eax")          
          $file.puts("#{$functions[$functions.length-1]}_logical#{$local_logicals}:")
          putsFile(nil, "pop", "eax")          
          $local_logicals += 1        
          putsFile(nil, "cmp", "eax", 0)
          $file.puts("; && ここまで(#{node[1]}, #{node[2]})")        
        when "||"
          $file.puts("; || ここから(#{node[1]}, #{node[2]})")
          putsFile(nil, "mov", "eax", "1")
          putsFile(nil, "push", "eax")          
          if node[1][0].instance_of?(String) == false || node[1][0] == "&&" || node[1][0] == "||"
            logical(node[1], lv)
          else
            comp(node[1], lv)
          end
          putsFile(nil, "cmp", "eax", "0")          
          putsFile(nil, "jne", "#{$functions[$functions.length-1]}_logical#{$local_logicals}")
          if node[1][0].instance_of?(String) == false || node[2][0] == "&&" || node[2][0] == "||"
            logical(node[2], lv)
          else
            comp(node[2], lv)
          end
          putsFile(nil, "cmp", "eax", "0")          
          putsFile(nil, "jne", "#{$functions[$functions.length-1]}_logical#{$local_logicals}")
          putsFile(nil, "pop", "eax")
          putsFile(nil, "mov", "eax", "0")
          putsFile(nil, "push", "eax")          
          $file.puts("#{$functions[$functions.length-1]}_logical#{$local_logicals}:")
          putsFile(nil, "pop", "eax")          
          $local_logicals += 1        
          putsFile(nil, "cmp", "eax", 0)
          $file.puts("; || ここまで(#{node[1]}, #{node[2]})")        
        end
      end
      
      if base_node[0] == "&&" || base_node[0] == "||"
        logical(base_node, lv)
      else
        comp(base_node, lv)
      end
    end

    # 現在見ているノード(配列)が最も深いノードか調べる
    leaf = true
    for n in child_node
      if n.instance_of?(String) == false
        leaf = false
        break
      end
    end

    # ノードの先頭要素が文字列なら、再帰的にコード生成処理を行う
    # 宣言文以外で葉だったなら、再帰末端用コードを生成する
    if child_node[0].instance_of?(String) == true
      case child_node[0]
      when "int"
        # 関数宣言または変数宣言
        # 関数 => ("int", "#{name}:#{type}:level#{level}")
        # 変数 => ("int", "#{name}:#{type}:level#{level}(#{pos})")
        child_node[1] =~ /(.+):(.+):(.+)/
        name = $1
        type = $2
        level = $3
        pos = nil
        if level.index("level0") == nil
          # パラメータかローカル変数
          child_node[1] =~ /(.+):(.+):level(.+)\((.+)\)/
          level = $3.to_i
          pos = $4.to_i
        else
          # 大域関数か大域変数
          level =~ /level(.+)/
          level = $1.to_i
        end
        if level == 0
          # 大域関数か大域変数のとき
          if type == "VAR"
            # 大域変数のとき
            putsFile(nil, "GLOBAL", name)
            putsFile(nil, "COMMON", "#{name} 4")
          elsif type == "FUN"
            # 大域関数の時
            $functions.push(name)
            putsFile(nil, "GLOBAL", name)
            putsFile(name, "push", "ebp")           
            putsFile(nil, "mov", "ebp", "esp")
            $n_local = 0
            culcNLocal(parent_node[2])
            putsFile(nil, "sub", "esp", "#{$n_local}")
            
            $file.puts("; 関数#{name}の本体ここから")
            for grandchild in parent_node[1]
              digTree(child_node, grandchild, lvl + 1)
            end
            for grandchild in parent_node[2]
              digTree(child_node, grandchild, lvl + 1)
            end
            $file.puts("; 関数#{name}の本体ここまで")
            
            putsFile("#{name}_ret", "mov", "esp", "ebp")
            putsFile(nil, "pop", "ebp")
            putsFile(nil, "ret")
            $local_vars.clear
            $local_ifs = 0
            $local_whiles = 0
            $local_logicals = 0
          end
        else
          $local_vars["#{name}:#{type}:level#{level}"] = pos
          $file.puts("; local_vars: #{name}:#{type}:level#{level} => #{pos}")
        end
      when "WHILE"
        $file.puts("; WHILEここから")
        $file.puts("#{$functions[$functions.length-1]}_whilestart#{$local_whiles}:")
        writeComp(child_node[1], lvl)
        putsFile(nil, "je", "#{$functions[$functions.length-1]}_whileend#{$local_whiles}")
        for grandchild in child_node[2]
          digTree(child_node[2], grandchild, lvl + 1)
        end
        putsFile(nil, "jmp", "#{$functions[$functions.length-1]}_whilestart#{$local_whiles}")
        $file.puts("#{$functions[$functions.length-1]}_whileend#{$local_whiles}:")
        $local_whiles += 1
        $file.puts("; WHILEここまで")
      when "IF"
        $file.puts("; IFここから")
        writeComp(child_node[1], lvl)
        putsFile(nil, "je", "#{$functions[$functions.length-1]}_if#{$local_ifs}")
        for grandchild in child_node[2]
          digTree(child_node[2], grandchild, lvl + 1)
        end
        $file.puts("#{$functions[$functions.length-1]}_if#{$local_ifs}:")
        $local_ifs += 1
        $file.puts("; この先else")
        for grandchild in child_node[3]
          digTree(child_node[3], grandchild, lvl + 1)
        end
        $file.puts("; IFここまで")
      when "FCALL"
        # 引数に数式が使われている場合は上手くいかないので、もう少し検討する
        child_node[2].length.times do |i|
          if child_node[2][child_node[2].length-1-i].instance_of?(String) == true || child_node[2][child_node[2].length-1-i].instance_of?(Fixnum) == true
            putsFile(nil, "mov", "eax", leafToCode(child_node[2][child_node[2].length-1-i]))
          else
            digTree(child_node[2], child_node[2][child_node[2].length-1-i], lvl + 1)
          end
          putsFile(nil, "push", "eax")
        end
        if $functions.index(child_node[1]) == nil
          putsFile(nil, "EXTERN", child_node[1])          
        end
        putsFile(nil, "call", child_node[1])
        child_node[2].length.times do |i|
          putsFile(nil, "pop", "ebx")
        end
      when "RETURN"
        # 戻り値をeaxに設定してreturnラベルに飛ぶ
        if child_node[1].instance_of?(String) == true || child_node[1].instance_of?(Fixnum) == true
          putsFile(nil, "mov", "eax", leafToCode(child_node[1]))
        else
          digTree(child_node, child_node[1], lvl + 1)
        end
        putsFile(nil, "jmp", "#{$functions[$functions.length - 1]}_ret")        

      when "="
        # 代入命令
        $file.puts("; = ここから(#{child_node[1]}, #{child_node[2]})")
        if child_node[2].instance_of?(String) == true
          putsFile(nil, "mov", leafToCode(child_node[1]), leafToCode(child_node[2]))
        elsif child_node[2].instance_of?(Fixnum) == true
          putsFile(nil, "mov", "eax", leafToCode(child_node[2]))
          putsFile(nil, "mov", leafToCode(child_node[1]), "eax")          
        else
          digTree(child_node, child_node[2], lvl + 1)
          putsFile(nil, "mov", leafToCode(child_node[1]), "eax")
        end
        $file.puts("; = ここまで(#{child_node[1]}, #{child_node[2]})")
      when "+"
        # 加算命令
        $file.puts("; + ここから(#{child_node[1]}, #{child_node[2]})")
        if child_node[2].instance_of?(String) == true || child_node[2].instance_of?(Fixnum) == true
          putsFile(nil, "mov", "eax", leafToCode(child_node[2]))          
          putsFile(nil, "push", "eax")
        else
          digTree(child_node, child_node[2], lvl + 1)
          putsFile(nil, "push", "eax")
        end
        if child_node[1].instance_of?(String) == true || child_node[1].instance_of?(Fixnum) == true
          putsFile(nil, "mov", "eax", leafToCode(child_node[1]))
        else
          digTree(child_node, child_node[1], lvl + 1)
        end
        putsFile(nil, "pop", "ebx")        
        putsFile(nil, "add", "eax", "ebx")
        $file.puts("; + ここまで(#{child_node[1]}, #{child_node[2]})")
      when "-"
        # 減算命令
        $file.puts("; - ここから(#{child_node[1]}, #{child_node[2]})")
        if child_node[2].instance_of?(String) == true || child_node[2].instance_of?(Fixnum) == true
          putsFile(nil, "mov", "eax", leafToCode(child_node[2]))          
          putsFile(nil, "push", "eax")
        else
          digTree(child_node, child_node[2], lvl + 1)
          putsFile(nil, "push", "eax")
        end
        if child_node[1].instance_of?(String) == true || child_node[1].instance_of?(Fixnum) == true
          putsFile(nil, "mov", "eax", leafToCode(child_node[1]))
        else
          digTree(child_node, child_node[1], lvl + 1)
        end
        putsFile(nil, "pop", "ebx")        
        putsFile(nil, "sub", "eax", "ebx")
        $file.puts("; - ここまで(#{child_node[1]}, #{child_node[2]})")
      when "*"
        # 乗算命令
        $file.puts("; * ここから(#{child_node[1]}, #{child_node[2]})")
        if child_node[2].instance_of?(String) == true || child_node[2].instance_of?(Fixnum) == true
          putsFile(nil, "mov", "eax", leafToCode(child_node[2]))          
          putsFile(nil, "push", "eax")
        else
          digTree(child_node, child_node[2], lvl + 1)
          putsFile(nil, "push", "eax")
        end
        if child_node[1].instance_of?(String) == true || child_node[1].instance_of?(Fixnum) == true
          putsFile(nil, "mov", "eax", leafToCode(child_node[1]))
        else
          digTree(child_node, child_node[1], lvl + 1)
        end
        putsFile(nil, "pop", "ebx")        
        putsFile(nil, "imul", "eax", "ebx")
        $file.puts("; * ここまで(#{child_node[1]}, #{child_node[2]})")
      when "/"
        # 除算命令
        $file.puts("; / ここから(#{child_node[1]}, #{child_node[2]})")
        if child_node[2].instance_of?(String) == true || child_node[2].instance_of?(Fixnum) == true
          putsFile(nil, "mov", "eax", leafToCode(child_node[2]))          
          putsFile(nil, "push", "eax")
        else
          digTree(child_node, child_node[2], lvl + 1)
          putsFile(nil, "push", "eax")
        end
        if child_node[1].instance_of?(String) == true || child_node[1].instance_of?(Fixnum) == true
          putsFile(nil, "mov", "eax", leafToCode(child_node[1]))
        else
          digTree(child_node, child_node[1], lvl + 1)
        end
        putsFile(nil, "cdq")
        putsFile(nil, "pop", "ebx")        
        putsFile(nil, "idiv", "dword ebx")
        $file.puts("; / ここまで(#{child_node[1]}, #{child_node[2]})")
      end    

    else
      if lvl < 0
        for grandchild in child_node
          digTree(child_node, grandchild, lvl + 1)
        end
      else
          digTree(child_node, child_node[0], lvl + 1)        
      end
    end
  end
  digTree(nil, tree)
end





parser = Tinyc.new

str = ''
while true
  add = gets
  if add == nil
    break
  else
    str += add
  end
end
if str != nil
  str.chop!
  begin
    puts "parse success!!!"
    tree = parser.parse(str)
    puts " result => \n#{tree}"
    generateAssemble(tree)
  rescue ParseError
    puts $!
  end
end
