#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.11
# from Racc grammer file "".
#

require 'racc/parser.rb'

# $Id: calc.y,v 1.4 2005/11/20 13:29:32 aamine Exp $
class Tinyc < Racc::Parser

module_eval(<<'...end compiler.y/module_eval...', 'compiler.y', 111)
  
  def parse(str)
    @q = []
    until str.empty?
      case str
      when /\A\s+/
      when /\A\d+/
        @q.push [:CONSTANT, $&.to_i]
      when /\A[a-zA-Z]\w*/
	@q.push [:IDENTIFIER, $&]
      when /\A.|\n/o
        s = $&
        @q.push [s, s]
      end
      str = $'
    end
    @q.push [false, '$end']
    do_parse
  end

  def next_token
    @q.shift
  end

...end compiler.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    50,     6,    56,    56,    56,   101,    99,   100,    50,    65,
    31,    50,    42,    53,    50,    34,     5,    35,    36,    24,
    77,    53,    52,    42,    53,    50,    77,    53,    55,    56,
    52,    66,    67,    52,    62,    31,    52,    42,    53,    50,
    34,    60,    35,    36,    24,    74,    75,    52,    64,    31,
    50,    42,    53,    50,    34,    50,    35,    36,    24,    72,
    73,    52,    77,    53,    58,    77,    53,    77,    53,    50,
    64,    50,    52,    50,    57,    52,    50,    52,    63,    72,
    73,    77,    53,    77,    53,    42,    53,    50,    42,    53,
    50,    52,    26,    52,    65,    52,    72,    73,    52,    77,
    53,    50,    77,    53,    68,    69,    70,    71,   102,    52,
   103,    31,    52,    42,    53,    50,    34,    50,    35,    36,
    24,    50,    10,    52,    72,    73,    26,    42,    53,    42,
    53,    19,    50,    42,    53,    50,    24,    52,    50,    52,
    50,    72,    73,    52,    42,    53,    50,    42,    53,    10,
    77,    53,    77,    53,    52,    21,    31,    52,    42,    53,
    52,    34,    52,    35,    36,    24,    50,    20,    52,    50,
    68,    69,    70,    71,    68,    69,    70,    71,    77,    53,
    19,    77,    53,    74,    75,    74,    75,    10,    52,    12,
    13,    52,    66,    67,    82,    56,    14,    11,    10,   107,
     5 ]

racc_action_check = [
   107,     1,    81,    78,    80,    81,    78,    80,    71,    43,
   107,   103,   107,   107,    70,   107,     1,   107,   107,   107,
    71,    71,   107,   103,   103,   101,    70,    70,    32,    32,
    71,    88,    88,   103,    41,   101,    70,   101,   101,   100,
   101,    37,   101,   101,   101,    47,    47,   101,    77,   100,
    69,   100,   100,    68,   100,    67,   100,   100,   100,    46,
    46,   100,    69,    69,    35,    68,    68,    67,    67,    66,
    42,    65,    69,    64,    34,    68,    63,    67,    42,    91,
    91,    66,    66,    65,    65,    64,    64,    62,    63,    63,
    72,    66,    29,    65,    83,    64,    92,    92,    63,    62,
    62,    27,    72,    72,    90,    90,    90,    90,    85,    62,
    87,    27,    72,    27,    27,    58,    27,    57,    27,    27,
    27,    56,    26,    27,    93,    93,    24,    58,    58,    57,
    57,    21,    53,    56,    56,    36,    20,    58,    75,    57,
    73,    94,    94,    56,    53,    53,    39,    36,    36,    19,
    75,    75,    73,    73,    53,    18,    39,    36,    39,    39,
    75,    39,    73,    39,    39,    39,    50,    16,    39,    74,
    45,    45,    45,    45,    89,    89,    89,    89,    50,    50,
    14,    74,    74,    95,    95,    96,    96,    13,    50,     8,
     8,    74,    44,    44,    59,    59,     9,     6,     5,   104,
     0 ]

racc_action_pointer = [
   185,     1,   nil,   nil,   nil,   180,   197,   nil,   173,   177,
   nil,   nil,   nil,   169,   165,   nil,   147,   nil,   138,   131,
   111,   116,   nil,   nil,   111,   nil,   104,    95,   nil,    77,
   nil,   nil,    12,   nil,    55,    45,   129,    15,   nil,   140,
   nil,    20,    51,    -4,   181,   163,    54,    43,   nil,   nil,
   160,   nil,   nil,   126,   nil,   nil,   115,   111,   109,   178,
   nil,   nil,    81,    70,    67,    65,    63,    49,    47,    44,
     8,     2,    84,   134,   163,   132,   nil,    29,   -14,   nil,
   -13,   -15,   nil,    81,   nil,    88,   nil,    93,    20,   167,
    97,    74,    91,   119,   136,   181,   183,   nil,   nil,   nil,
    33,    19,   nil,     5,   177,   nil,   nil,    -6,   nil ]

racc_action_default = [
   -64,   -64,    -1,    -3,    -4,   -64,   -64,    -2,   -64,    -6,
    -8,   109,    -5,   -64,   -13,    -7,   -64,   -10,   -12,   -64,
   -64,   -64,   -14,    -9,   -26,   -11,   -64,   -30,   -23,   -25,
    -6,   -15,   -64,   -17,   -64,   -64,   -64,   -64,   -27,   -29,
   -31,   -33,   -57,   -35,   -37,   -39,   -42,   -47,   -50,   -53,
   -64,   -55,   -58,   -64,   -24,   -16,   -64,   -64,   -64,   -64,
   -22,   -28,   -64,   -64,   -63,   -64,   -64,   -64,   -64,   -64,
   -64,   -64,   -64,   -64,   -64,   -64,   -54,   -57,   -64,   -32,
   -64,   -64,   -21,   -36,   -34,   -64,   -60,   -62,   -38,   -40,
   -41,   -43,   -44,   -45,   -46,   -48,   -49,   -51,   -52,   -59,
   -64,   -64,   -56,   -64,   -18,   -20,   -61,   -64,   -19 ]

racc_goto_table = [
    38,    79,    76,    59,    17,    28,    37,     9,    84,    86,
    54,    25,    61,    89,    90,    15,    91,    92,    93,    94,
    78,    22,    95,    96,    80,    81,    97,    98,    30,     2,
     7,    29,    39,    27,    83,    88,    18,    23,    16,     1,
    85,    87,   nil,   nil,   nil,   nil,   nil,   nil,   106,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   104,   105,   nil,   nil,   nil,   nil,   nil,
   108 ]

racc_goto_check = [
    11,    17,    24,    12,    10,     3,    14,     6,    17,    17,
     3,    10,    11,    21,    21,     6,    22,    22,    22,    22,
    12,     6,    23,    23,    12,    12,    24,    24,     6,     2,
     2,    15,    16,    13,    19,    20,     9,     8,     7,     1,
    27,    28,   nil,   nil,   nil,   nil,   nil,   nil,    17,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    11,    11,   nil,   nil,   nil,   nil,   nil,
    11 ]

racc_goto_pointer = [
   nil,    39,    29,   -19,   nil,   nil,     2,    24,    17,    22,
   -10,   -27,   -33,     9,   -21,     7,     5,   -55,   nil,   -28,
   -30,   -53,   -52,   -50,   -48,   nil,   nil,   -24,   -23 ]

racc_goto_default = [
   nil,   nil,   nil,     3,     4,     8,   nil,   nil,    33,   nil,
   nil,   nil,    32,   nil,   nil,   nil,   nil,    40,    41,    43,
    44,    45,    46,    47,    48,    49,    51,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 30, :_reduce_none,
  2, 30, :_reduce_none,
  1, 31, :_reduce_none,
  1, 31, :_reduce_none,
  3, 32, :_reduce_none,
  1, 34, :_reduce_none,
  3, 34, :_reduce_none,
  1, 35, :_reduce_none,
  6, 33, :_reduce_none,
  1, 38, :_reduce_none,
  3, 38, :_reduce_none,
  1, 36, :_reduce_none,
  0, 36, :_reduce_none,
  2, 39, :_reduce_none,
  1, 40, :_reduce_none,
  2, 40, :_reduce_none,
  1, 40, :_reduce_none,
  5, 40, :_reduce_none,
  7, 40, :_reduce_none,
  5, 40, :_reduce_none,
  3, 40, :_reduce_none,
  4, 37, :_reduce_none,
  1, 44, :_reduce_none,
  2, 44, :_reduce_none,
  1, 42, :_reduce_none,
  0, 42, :_reduce_none,
  1, 45, :_reduce_none,
  2, 45, :_reduce_none,
  1, 43, :_reduce_none,
  0, 43, :_reduce_none,
  1, 41, :_reduce_none,
  3, 41, :_reduce_none,
  1, 46, :_reduce_none,
  3, 46, :_reduce_none,
  1, 47, :_reduce_none,
  3, 47, :_reduce_none,
  1, 48, :_reduce_none,
  3, 48, :_reduce_none,
  1, 49, :_reduce_none,
  3, 49, :_reduce_none,
  3, 49, :_reduce_none,
  1, 50, :_reduce_none,
  3, 50, :_reduce_none,
  3, 50, :_reduce_none,
  3, 50, :_reduce_none,
  3, 50, :_reduce_none,
  1, 51, :_reduce_none,
  3, 51, :_reduce_none,
  3, 51, :_reduce_none,
  1, 52, :_reduce_none,
  3, 52, :_reduce_none,
  3, 52, :_reduce_none,
  1, 53, :_reduce_none,
  2, 53, :_reduce_none,
  1, 54, :_reduce_none,
  4, 54, :_reduce_none,
  1, 55, :_reduce_none,
  1, 55, :_reduce_none,
  3, 55, :_reduce_none,
  1, 57, :_reduce_none,
  3, 57, :_reduce_none,
  1, 56, :_reduce_none,
  0, 56, :_reduce_none ]

racc_reduce_n = 64

racc_shift_n = 109

racc_token_table = {
  false => 0,
  :error => 1,
  "*" => 2,
  "/" => 3,
  "%" => 4,
  "+" => 5,
  "-" => 6,
  "<" => 7,
  ">" => 8,
  "<=" => 9,
  ">=" => 10,
  "==" => 11,
  "!=" => 12,
  "&&" => 13,
  "||" => 14,
  "int" => 15,
  ";" => 16,
  "," => 17,
  :IDENTIFIER => 18,
  "(" => 19,
  ")" => 20,
  "if" => 21,
  "else" => 22,
  "while" => 23,
  "return" => 24,
  "{" => 25,
  "}" => 26,
  "=" => 27,
  :CONSTANT => 28 }

racc_nt_base = 29

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "\"*\"",
  "\"/\"",
  "\"%\"",
  "\"+\"",
  "\"-\"",
  "\"<\"",
  "\">\"",
  "\"<=\"",
  "\">=\"",
  "\"==\"",
  "\"!=\"",
  "\"&&\"",
  "\"||\"",
  "\"int\"",
  "\";\"",
  "\",\"",
  "IDENTIFIER",
  "\"(\"",
  "\")\"",
  "\"if\"",
  "\"else\"",
  "\"while\"",
  "\"return\"",
  "\"{\"",
  "\"}\"",
  "\"=\"",
  "CONSTANT",
  "$start",
  "program",
  "external_declaration",
  "declaration",
  "function_definition",
  "declarator_list",
  "declarator",
  "parameter_type_list_opt",
  "compound_statement",
  "parameter_type_list",
  "parameter_declaration",
  "statement",
  "expression",
  "declaration_list_opt",
  "statement_list_opt",
  "declaration_list",
  "statement_list",
  "assign_expr",
  "logical_OR_expr",
  "logical_AND_expr",
  "equality_expr",
  "relational_expr",
  "add_expr",
  "mult_expr",
  "unary_expr",
  "posifix_expr",
  "primary_expr",
  "argument_expression_list_opt",
  "argument_expression_list" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

# reduce 18 omitted

# reduce 19 omitted

# reduce 20 omitted

# reduce 21 omitted

# reduce 22 omitted

# reduce 23 omitted

# reduce 24 omitted

# reduce 25 omitted

# reduce 26 omitted

# reduce 27 omitted

# reduce 28 omitted

# reduce 29 omitted

# reduce 30 omitted

# reduce 31 omitted

# reduce 32 omitted

# reduce 33 omitted

# reduce 34 omitted

# reduce 35 omitted

# reduce 36 omitted

# reduce 37 omitted

# reduce 38 omitted

# reduce 39 omitted

# reduce 40 omitted

# reduce 41 omitted

# reduce 42 omitted

# reduce 43 omitted

# reduce 44 omitted

# reduce 45 omitted

# reduce 46 omitted

# reduce 47 omitted

# reduce 48 omitted

# reduce 49 omitted

# reduce 50 omitted

# reduce 51 omitted

# reduce 52 omitted

# reduce 53 omitted

# reduce 54 omitted

# reduce 55 omitted

# reduce 56 omitted

# reduce 57 omitted

# reduce 58 omitted

# reduce 59 omitted

# reduce 60 omitted

# reduce 61 omitted

# reduce 62 omitted

# reduce 63 omitted

def _reduce_none(val, _values, result)
  val[0]
end

end   # class Tinyc


parser = Tinyc.new
puts
puts 'type "Q" to quit.'
puts
while true
  puts
  print '? '
  str = gets.chop!
  break if /q/i =~ str
  begin
    puts "= #{parser.parse(str)}"
  rescue ParseError
    puts $!
  end
end
